package main

var allergenCodeToName = map[string]string{
	"Ei":  "Eier",
	"En":  "Erdnüsse",
	"Fi":  "Fisch",
	"GlD": "Dinkel",
	"GlG": "Gerste",
	"GlH": "Hafer",
	"GlK": "Kamut",
	"GlR": "Roggen",
	"GlW": "Weizen",
	"Kr":  "Krebstiere",
	"Lu":  "Lupinen",
	"Mi":  "Milch und Laktose",
	"NC":  "Cashewnüsse",
	"NH":  "Haselnüsse",
	"NMc": "Macadamianüsse",
	"NMn": "Mandeln",
	"NPa": "Paranüsse",
	"NPe": "Pekannüsse",
	"NPi": "Pistazien",
	"NW":  "Walnüsse",
	"Se":  "Sesam",
	"Sf":  "Senf",
	"Sl":  "Sellerie",
	"So":  "Soja",
	"Sw":  "Schwefeldioxid und Sulfite",
	"Wt":  "Weichtiere",
}
